# Generated by Django 3.2 on 2022-12-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField(blank=True)),
                ('container_title', models.CharField(blank=True, max_length=200)),
                ('container_info', models.CharField(blank=True, max_length=200)),
                ('ssh_ip', models.CharField(blank=True, max_length=200)),
                ('ssh_username', models.CharField(blank=True, max_length=200)),
                ('ssh_password', models.CharField(blank=True, max_length=200)),
                ('is_deployed', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'containers',
            },
        ),
    ]
